wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
num_conv_blocks:
  desc: null
  value: 3
dataset:
  desc: null
  value: CatDogFull
epochs:
  desc: null
  value: 30
units_shape:
  desc: null
  value: 10
TrivialAugmentWide:
  desc: null
  value: 15
loss_fn:
  desc: null
  value: CrossEntropyLoss
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710451100.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
